[functions.admin-create-member]
enabled = true
verify_jwt = true
import_map = "./functions/admin-create-member/deno.json"
entrypoint = "./functions/admin-create-member/index.ts"

[functions.send-push]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-push/index.ts"

[functions.publish-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/publish-notification/index.ts"

[functions.send-birthday-notifications]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-birthday-notifications/index.ts"

[functions.publish-scheduled-notifications]
enabled = true
verify_jwt = false
entrypoint = "./functions/publish-scheduled-notifications/index.ts"

[functions.send-post-class-reminders]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-post-class-reminders/index.ts"


[functions.cleanup-old-notifications]
verify_jwt = false
entrypoint = "./functions/cleanup-old-notifications/index.ts"

[functions.create-membership-payment-intent]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-membership-payment-intent/index.ts"

[functions.create-my-membership-payment-intent]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-my-membership-payment-intent/index.ts"

