// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPyFvlgJAD8AiePP6ooBVTUiqvLON4HVQ',
    appId: '1:750860892649:web:494598e4d6cb379269b378',
    messagingSenderId: '750860892649',
    projectId: 'athlete-lab-app',
    authDomain: 'athlete-lab-app.firebaseapp.com',
    storageBucket: 'athlete-lab-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PhX9LU1RATgfmJt75eZGUaarok8gYdM',
    appId: '1:750860892649:android:c9cf0a258adf28de69b378',
    messagingSenderId: '750860892649',
    projectId: 'athlete-lab-app',
    storageBucket: 'athlete-lab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVrHGDjKdQVSSxDeSYGJO7gH3DUmadvbY',
    appId: '1:750860892649:ios:d41011ca98f1034c69b378',
    messagingSenderId: '750860892649',
    projectId: 'athlete-lab-app',
    storageBucket: 'athlete-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.ath615',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVrHGDjKdQVSSxDeSYGJO7gH3DUmadvbY',
    appId: '1:750860892649:ios:d41011ca98f1034c69b378',
    messagingSenderId: '750860892649',
    projectId: 'athlete-lab-app',
    storageBucket: 'athlete-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.ath615',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPyFvlgJAD8AiePP6ooBVTUiqvLON4HVQ',
    appId: '1:750860892649:web:19b49927e3bb1c9669b378',
    messagingSenderId: '750860892649',
    projectId: 'athlete-lab-app',
    authDomain: 'athlete-lab-app.firebaseapp.com',
    storageBucket: 'athlete-lab-app.firebasestorage.app',
  );
}
